#server:
#  port: 8080
# порт сервиса


spring:
 # main.web-application-type: reactive
  cloud:
    gateway:
      discovery.locator.enabled: true




      routes:
        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/admin/events/**,/users/{userId}/events/**,/events/**

        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,/users/{userId}/comments/**,/comments/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**


management:
  endpoints:
    web:
      exposure:
        include: health,info
